### ISSUE TITLE
Export default for tsx files

### ISSUE THREAD

**Issue by Maciejlys** [solidjs-community/solid-snippets#9]
Please add export default to tsx snippets, its annoying to add them by hand, any reason why they are excluded but they work in jsx files?

**Comment by thetarnav** [comment]
What if the component is meant to be used only locally, or it should be a named export, or the component is defined inside another?
I guess defaulting to having `export` for every component should be fine. Often the components are created to be used elsewhere, and `export` can be easily removed or `default` added if necessary.
The only place `export default` makes sense is page components in file-based routing. And for that, we should probably have a different snippet honestly. With `routeData` and other things already in place.

**Comment by Maciejlys** [comment]
Then why would you have default exports for jsx but not for tsx? If you think there should be none, keep it consistent and remove it from jsx. Imo it should be there in all snippets but the one that I am using the most rn is scompi

**Comment by thetarnav** [comment]
I agree about the inconsistency. I wasn't aware of it because I only use ts and tsx.
Would adding `export default` to snippets ending with `i`, so ones that import stuff, but leave the import-less snippets as they are? I imagine you'd use snippets with imports mainly when creating "single file components" where export default would make some sense. (although I prefer to use named exports almost always)

**Comment by Maciejlys** [comment]
Yeah it would make sense, or you can create separate snippet like scompie - import and export but then you would need to remove inconsistency in jsx snippets if you do that, the easiest approach would be to add exports to snippets that have it in jsx so it is consistent

**Comment by Maciejlys** [comment]
I opened a pr with requested change -> https://github.com/solidjs-community/solid-snippets/pull/10
